### ISSUE TITLE
Non-Obie institution role

### ISSUE THREAD

**Issue by aborroni** [OCTETatOC/Blackboard-UserDirectory#3]
Users with the Non-Obie institution role should be able to search the directory.
They should not be listed in the directory.
They should view info as  a student would view information.

**Comment by C0urante** [comment]
As in, the literal portal (or instiution) role of "Non-Obie", or anyone with a Portal Role that isn't Faculty, Emeriti, Alumni, Staff, or Student?

**Comment by C0urante** [comment]
The name of the role is "Non Obie".

**Comment by C0urante** [comment]
Added! People with this role can now use the tool, and are given non-privileged information (identical to what a student would see).
