### ISSUE TITLE
Connect faculty listing to the current smartclassroom info

### ISSUE THREAD

**Issue by aborroni** [OCTETatOC/Blackboard-UserDirectory#6]
Connect faculty to list of courses found in the classroom lookup tool.

**Comment by C0urante** [comment]
Is this still something we want to do, or did we decide it wasn't practical for now?

**Comment by Oberlin-OCTET** [comment]
Would love to still do this but I think it might be a bigger project that I
would need to be more involved in. Unfortunately, I don't have time now.

Work on syllabus repository!

Albert
